---
title: "Projects"
---

## Shiny Apps

### ACT Practice Test Dashboard

Student performance statistics is shown on the **Instructors Dashboard** found at the given Shiny link below.  It features a *Student Table* showing question-level performance, a *Tough Questions* portion stressing challenging topics, and a *Score Histogram* to help one view score distributions.  Targeting performance analysis, instructors can select data by *Test Period* (Pre-Test/Post-Test), *Test Subject* (English, Math, Science, Reading), and *Student Name*.

[Instructor's Dashboard](https://denisebradfordunl.shinyapps.io/Instructors_Dashboard/)

[Student's Dashboard](https://denisebradfordunl.shinyapps.io/Students/)

### UNL Athletics Department Dashboards

The following links of Shiny web applications related completed with Nebraska Athletics Department, specifically football, men's and women's basketball. However, accessing these applications requires user authentication, and without valid credentials.

[Football Dashbaord Scouting](https://denisebradfordunl.shinyapps.io/nebraska_fb/)

[Men's Basketball Scouting](https://denisebradfordunl.shinyapps.io/mbb_scouting_app/)

[Women's Basketball - Postgame Reports](https://denisebradfordunl.shinyapps.io/wbb_postgame_report/)
