---
title: "About"
---

# More About Me

My academic work emphasizes interactive dashboards, open-source data access, analytical tools catered for sports analytics and community decision-making.  Under a National Science Foundation project on "Smart Decision-Making in Small and Shrinking Rural Areas," I have particularly focused on clean, open-source data creation using web scraping and geospatial analysis.  Studies addressing geographic analytics, predictive modeling, and interactive dashboard design have also been published in peer-reviewed publications.

Beyond research, I love to teach and have led seminars on programming in R, statistical modeling, and tidy data techniques. By always striving to make statistical methods accessible, useful, and actionable, I hope to close the gap between scholarly theory and actual applications.

When I'm not busy with work or school, I love watching sports, especially basketball and football. I’m the Communications Chair for the Statistics in Sports Section of the American Statistical Association (ASA) and along with the Finance Chair for Revitalize Our Communities (ROC). You can usually catch me creating cool structures with magnet tiles with my nieces and nephews. 


For further information, visit my [GitHub projects](https:// github.com/drbradford12) or view my [resume here](https://drbradford12.github.io/my_website/resume/).
Please feel free to [contact me](mailto:mail.deniserbradford@gmail.com) if you have any questions or would like to discuss potential projects.

## Education

**University of Nebraska, Lincoln** | Lincoln, NE

PhD in Statistics | Aug 2020 - Present

**University of Nebraska, Lincoln** | Lincoln, NE

M.S in Statistics | Aug 2018 - May 2020

**Purdue University** | West Lafayette, IN

M.S in Applied Statistics | Dec 2010 - May 2012

**Purdue University** | West Lafayette, IN

B.S in Applied Statistics | Aug 2004 - Dec 2008

## Experience

**Detroit Pistons** | Senior Data Scientist | December 2022 - August 2024

**Philadelphia 76ers** | Data Scientist |  June 2022 - December 2022

**Nebraska Athletics Performance Lab** | Sports Analytics Assistant |  June 2021 - May 2022

**Hudl** | Data Analyst Intern |  June 2019 - June 2021



