---
title: "Publications"
---

"Consonant production accuracy in young cochlear implant recipients: Developmental sound classes and word position effects"
DJ Ertmer, DT Kloiber, J Jung, KC Kirleis, D Bradford
American Speech-Language-Hearing Association Rockville, MD 

[Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=BHtAGp4AAAAJ&citation_for_view=BHtAGp4AAAAJ:Tyk-4Ss8FVUC)

"Environmental Regulation of Heterosis in the Allopolyploid Arabidopsis suecica"
EM Solhaug, J Ihinger, M Jost, V Gamboa, B Marchant, D Bradford, et. al
Plant Physiology 170 (4), 2251-2263

[Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=BHtAGp4AAAAJ&citation_for_view=BHtAGp4AAAAJ:UeHWp8X0CEIC)

"Factors associated with pregnancy among incarcerated African American adolescent girls"
SC Gray, K Holmes, DR Bradford
Journal of Urban Health 93, 709-718

[Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=BHtAGp4AAAAJ&citation_for_view=BHtAGp4AAAAJ:zYLM7Y9cAGgC)

"Exploring Rural Shrink Smart Through Guided Discovery Dashboards"
D Bradford, S VanderPlas
Journal of Data Science

[Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=BHtAGp4AAAAJ&citation_for_view=BHtAGp4AAAAJ:_FxGoFyzp5QC)

"Geospatial assessment of phenotype predictive analytics using machine learning techniques"
F Munoz-Arriola, P Sarzaeim, A Amaranto, D Jarquin, D Bradford
Geophysical Research Abstracts 21

[Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=BHtAGp4AAAAJ&citation_for_view=BHtAGp4AAAAJ:W7OEmFMy1HYC)
